name: clojureflare

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt update && sudo apt install -y leiningen
    - name: lein build
      run: |
        lein cljsbuild once production
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt update && sudo apt install -y leiningen
    - name: lein test
      run: |
        lein test | grep "All tests succeeded!"
  create-worker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt update && sudo apt install -y leiningen
    - name: lein jar
      run: lein jar
    - name: compile example
      run: cd example-worker && lein compile
    - name: run worker
      run: wrangler preview -u https://example.com/v1/api/test --headless | grep 'cool response'

