name: Github Pages Docs
on:
  push:
    branches:
      - main
    tags:        
      - '**'
jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install deps
      run: |
        sudo apt update && sudo apt install -y leiningen
    - name: Build docs
      run: |
        lein codox
    - name: Publish
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: target/doc
